# Alacritty configuration file
#
# See https://alacritty.org/config/ for more detailed configuration options.

# Font configuration
[font]

size = 13

  [font.normal]
  family = "Inconsolata"

  [font.bold]
  family = "Inconsolata"

  # Glyph offset (no change from default, but included for completeness)
  [font.glyph_offset]
  x = 0
  y = 0

# Window configuration
[window]

# Startup opacity (transparency)
opacity = 0.75

# Window padding
padding = { x = 0, y = 0 }

# Decorations
decorations = "none" # or "full", "transparent", "buttonless"

# Shell configuration
[terminal.shell]
program = "/bin/zsh"

# Colors configuration
[colors]

  # Default colors
  [colors.primary]
  background = "#0a001f"
  foreground = "#d9d5e6"

  # Cursor colors
  [colors.cursor]
  text = "#0a001f"
  cursor = "#d9d5e6"

  # Normal colors
  [colors.normal]
  black   = "#828ff9"
  red     = "#6740ba"
  green   = "#828ff9"
  yellow  = "#ac96dc"
  blue    = "#e94c80"
  magenta = "#ace6f0"
  cyan    = "#6740ba"
  white   = "#eebea4"

  # Bright colors
  [colors.bright]
  black   = "#828ff9"
  red     = "#6740ba"
  green   = "#828ff9"
  yellow  = "#ac96dc"
  blue    = "#e94c80"
  magenta = "#ace6f0"
  cyan    = "#6740ba"
  white   = "#ace6f0"

# Cursor style
[cursor]

style = { shape = "Beam", blinking = "Never" } # Changed to Beam for line cursor

thickness = 0.25 # Adjusted thickness for beam cursor, st's default is thin line
