#!/bin/bash

sudo cpupower frequency-set --governor performance

sudo cpupower frequency-set --freq 3.20GHz
sudo cpupower frequency-set --min 3.20GHz

sudo cpupower idle-set --disable 3
sudo cpupower idle-set --disable 2
sudo cpupower idle-set --disable 1
sudo cpupower idle-set --disable 0

#sudo cpupower idle-set --enable-all

sudo cpupower frequency-info
sudo cpupower monitor
