#!/bin/bash

set -eu

echo "


  _/      _/    _/_/    _/_/_/  _/_/_/
 _/      _/  _/    _/    _/    _/    _/
_/      _/  _/    _/    _/    _/    _/
 _/  _/    _/    _/    _/    _/    _/
  _/        _/_/    _/_/_/  _/_/_/



    _/        _/_/_/  _/      _/  _/    _/  _/      _/
   _/          _/    _/_/    _/  _/    _/    _/  _/
  _/          _/    _/  _/  _/  _/    _/      _/
 _/          _/    _/    _/_/  _/    _/    _/  _/
_/_/_/_/  _/_/_/  _/      _/    _/_/    _/      _/



    _/_/_/  _/      _/    _/_/_/  _/_/_/_/_/    _/_/    _/        _/
     _/    _/_/    _/  _/            _/      _/    _/  _/        _/
    _/    _/  _/  _/    _/_/        _/      _/_/_/_/  _/        _/
   _/    _/    _/_/        _/      _/      _/    _/  _/        _/
_/_/_/  _/      _/  _/_/_/        _/      _/    _/  _/_/_/_/  _/_/_/_/



      _/_/_/    _/_/_/  _/_/_/    _/_/_/  _/_/_/    _/_/_/_/_/
   _/        _/        _/    _/    _/    _/    _/      _/
    _/_/    _/        _/_/_/      _/    _/_/_/        _/
       _/  _/        _/    _/    _/    _/            _/
_/_/_/      _/_/_/  _/    _/  _/_/_/  _/            _/


"

echo "Make sure that you have already gone through the void-installer script provided by Void Linux."

echo "This script will install and configure a bunch of packages that I use for my usual setup."

echo ""

echo "Do you want to continue? (y/n)" ; read answer

echo ""

if [ "$answer" != "${answer#[Yy]}" ] ; then
    echo "Continuing..."
else
    echo "Exiting..."
    exit
fi

echo ""

echo "Updating package repositories and installing packages."

sudo xbps-install -SAu

sudo xbps-install -SAu void-repo-nonfree void-updates void-repo-multilib void-repo-multilib-nonfree

# To get the package list: xpkg -m | xargs -n 1 | xsel -b
# PROBLEMS: libglib-static-32bit, libgtkhtml, vkd3d-32bit
# SOLUTIONS: remove them from the list
sudo xbps-install -SAu \
7zip-unrar \
CPU-X \
Ghidrathon \
GraphicsMagick \
ImageMagick \
MangoHud \
Minder \
MultiMarkdown \
PopCorn \
RcloneBrowser \
SDL2-devel \
SDL2_ttf \
SDL2_ttf-devel \
SDL_image \
SFML \
SFML-devel \
Signal-Desktop \
SoapyAirspy \
SoapyHackRF \
SoapyLMS7 \
SoapyRTLSDR \
SoapyUHD \
Vulkan-Headers \
Vulkan-Tools \
Vulkan-ValidationLayers \
abook \
acpi \
acpi_call-dkms \
adwaita-qt \
aircrack-ng \
alacritty \
alsa-firmware \
alsa-lib-devel \
alsa-pipewire \
alsa-plugins \
alsa-plugins-ffmpeg \
alsa-plugins-samplerate \
alsa-tools \
alsa-tools-devel \
alsa-utils \
alsaequal \
amdvlk \
amdvlk-32bit \
amfora \
android-file-transfer-linux \
android-udev-rules \
ansible \
arc-icon-theme \
arc-theme \
ardour \
arduino-cli \
aria2 \
arp-scan \
arpfox \
artwiz-fonts \
ascii \
asciinema \
aspell \
aspell-en \
atool \
attr-devel \
audacious \
audacious-plugins \
autofs \
base-devel \
base-system \
bash-language-server \
bat \
binfmt-support \
blender \
blueman \
bluez \
bombardier \
bridge-utils \
brother-brlaser \
bsdtar \
bsdunzip \
btop \
cairomm-devel \
cargo \
catdoc \
catgirl \
cava \
cbonsai \
ccls \
cglm \
chromium \
ckb-next \
clamav \
clang \
clang-analyzer \
clang-analyzer17 \
clang-tools-extra \
clang19-headers \
clipmenu \
cloc \
clutter-gst \
clutter-gst-devel \
clutter-gst3 \
clutter-gst3-devel \
cmake \
cmark \
cmark-gfm \
cmatrix \
console-setup \
croc \
cronie \
cryptsetup \
cups \
cups-devel \
cups-filters \
cups-pdf \
curl \
cutter \
czkawka \
dcadec \
ddcutil \
dfc \
dina-font \
dino \
dmenu \
docker \
docker-buildx \
docker-compose \
dragon \
dumb_runtime_dir \
dunst \
earlyoom \
easyeffects \
ebook-tools \
eclipse \
edk2-ovmf \
electrum \
evince \
evtest \
exfatprogs \
exiftool \
ext4magic \
extundelete \
fail2ban \
fann \
farstream \
farstream-devel \
fastfetch \
fbv \
fd \
feh \
ffmpeg \
figlet \
figlet-fonts \
filezilla \
firefox \
flatpak \
foliate \
font-adobe-source-code-pro \
font-awesome \
font-awesome6 \
font-cozette \
font-firacode \
font-inconsolata-otf \
font-iosevka \
font-material-design-icons-ttf \
font-sil-doulos \
font-weather-icons \
fontconfig-doc \
fontforge \
fontmanager \
fonts-croscore-ttf \
fortune-mod \
fortune-mod-anarchism \
fortune-mod-de \
fortune-mod-void \
freecad \
fsv \
fuse-devel \
fuse-sshfs \
fuse3 \
fuse3-devel \
fzf \
gallery-dl \
gamemode \
gcc-fortran \
gcc-go \
gcolor3 \
gdb \
gdmap \
gdu \
geckodriver \
ghc \
ghc-doc \
ghi \
ghidra \
ghostwriter \
giflib-devel \
giflib-tools \
gimp \
git \
github-cli \
gitui \
glances \
glava \
glew-devel \
glfw-devel \
glib-devel \
glm \
glmark2 \
glxinfo \
gmic-krita \
gmpxx \
gmpxx-devel \
gnome-screenshot \
gnome-sound-recorder \
gnome-themes-extra \
gnome-video-effects \
gnuradio \
gnuradio-osmosdr \
go \
go-mtpfs \
godot \
golangci-lint \
gomatrix \
gopls \
gparted \
gperftools \
gperftools-32bit \
gperftools-devel \
gpgme \
gradle \
groff-doc \
grub-x86_64-efi \
gst-libav \
gst-plugins-good1-qt5 \
gst-plugins-ugly1 \
gst-rtsp-server \
gst-rtsp-server-devel \
gst1-editing-services \
gst1-editing-services-devel \
gst1-python3 \
gst123 \
gstreamer-vaapi \
gstreamer1-aravis \
gstreamer1-devel \
gstreamer1-pipewire \
gstreamermm \
gstreamermm-devel \
gtk+3-devel \
gtk-engine-murrine-32bit \
gtklp \
gtypist \
hashcat \
hashcat-utils \
hdf5-devel \
hidapi \
hidapi-devel \
highlight \
horst \
hplip \
htop \
hunspell-en \
hunspell-ro_RO \
hydrogen \
i2c-tools \
i2c-tools-32bit \
i2c-tools-devel \
i2pd \
icdiff \
icu-devel \
imlib2-devel \
imlib2-tools \
imlib2-webp \
inetutils \
inetutils-ifconfig \
inkscape \
inxi \
ipafont-fonts-otf \
isync \
jack \
jmtpfs \
jp2a \
jq \
json-c++ \
judy \
judy-devel \
jupyterlab \
kakoune \
kdenlive \
keepassxc \
kicad \
kompare \
kotlin-bin \
krfb \
krita \
kubernetes \
kvantum \
lagrange \
libX11-devel-32bit \
libXdamage-devel \
libXft-devel \
libXi-32bit \
libXinerama-devel \
libXrandr-32bit \
libXrandr-devel \
libXrandr-devel-32bit \
libXtst-32bit \
libcurl-devel \
libdazzle \
libdca \
libdrm-32bit \
liberation-fonts-ttf \
libexif-devel \
libfreeglut-devel \
libgcc-32bit \
libgfortran-devel \
libglib-static-32bit \
libglvnd-32bit \
libgo-32bit \
libgo-devel-32bit \
libgomp-32bit \
libgomp-devel \
libgomp-devel-32bit \
libgstreamerd \
libgstreamerd-devel \
libgta \
libgta-devel \
libgtkdgl-32bit \
libgtkdsv-32bit \
libgtkhtml-32bit \
libguestfs \
libinput-gestures \
libjack-pipewire \
libjpeg-turbo \
libnice-devel \
libopenal-32bit \
libopencv-devel \
libopencv-python3 \
libopencv4 \
libopencv4-devel \
libopencv4-python3 \
libopusenc \
libopusenc-devel \
libpulseaudio-32bit \
libreoffice \
libselinux \
libsixel \
libsixel-devel \
libsixel-util \
libspa-bluetooth \
libspa-jack \
libspa-vulkan \
libspa-vulkan-32bit \
libstdc++-32bit \
libstdc++-devel-32bit \
libva-32bit \
libvdpau-32bit \
libwoff2common1.0.2 \
libwoff2dec1.0.2 \
libwoff2enc1.0.2 \
libxcrypt-compat \
linux-driver-management \
linux-firmware \
linux-lts \
linux-lts-headers \
linux-mainline \
linux-mainline-headers \
linux-tools \
linux-vt-setcolors \
linux6.12 \
linux6.12-headers \
linux6.6 \
linux6.6-headers \
llvm \
lm_sensors \
love \
lsd \
lua \
lua-language-server \
luarocks \
lutris \
lynx \
macchanger \
mandown \
mathjax \
mathjax2 \
mdp \
mediainfo \
mesa-32bit \
mesa-ati-dri \
mesa-ati-dri-32bit \
mesa-demos \
mesa-dri-32bit \
mesa-opencl-32bit \
mesa-vulkan-intel \
mesa-vulkan-intel-32bit \
mesa-vulkan-overlay-layer \
mesa-vulkan-overlay-layer-32bit \
mesa-vulkan-radeon \
mesa-vulkan-radeon-32bit \
meson \
mokutil \
mosh \
mpop \
mpv \
mpv-mpris \
msmtp \
mtools \
mupdf \
nasm \
ncurses-devel \
ncurses-libtinfo-devel \
ncurses-libtinfo-libs \
nemesis \
neomutt \
neovim \
nerd-fonts \
netbsd-wtf \
newsboat \
nfs-utils \
nginx \
nicotine+ \
nix \
nmap \
notmuch \
noto-fonts-cjk \
noto-fonts-emoji \
ntfs-3g \
nv-codec-headers \
nvidia \
nvidia-container-toolkit \
nvidia-docker \
nvidia-libs-32bit \
nvidia-opencl \
nvimpager \
nvtop \
obs \
octave \
openblas-devel \
openbsd-netcat \
opencv \
opencv4 \
openjdk \
openjdk-jre \
openjdk17 \
openrgb \
opus-tools \
outguess \
p7zip \
pam-gnupg \
pandoc \
pango-devel \
pango-view \
pangomm-devel \
pass \
pass-otp \
pavucontrol \
pcmanfm \
pdfsandwich \
persepolis \
pgcli \
pgmetrics \
pgweb \
picom \
piper \
pipewire \
pipewire-devel \
pipewire-doc \
pixd \
pnpm \
podman \
podman-compose \
podman-tui \
ponysay \
poppler-qt6 \
poppler-utils \
postgresql \
postgresql-client \
postgresql-full \
postgrest \
powerstat \
powertop \
ppp \
profanity \
protontricks \
pulsemixer \
pyright \
python3-Markdown \
python3-cairo-devel \
python3-cairocffi \
python3-cchardet \
python3-commonmark \
python3-cycler \
python3-dbus-devel \
python3-devel \
python3-docutils \
python3-glad \
python3-h5py \
python3-html2text \
python3-lsp-server \
python3-markdown-math \
python3-mccabe \
python3-mpv \
python3-mypy \
python3-neovim \
python3-pip \
python3-pipx \
python3-pycodestyle \
python3-pyflakes \
python3-pymediainfo \
python3-pyside6 \
python3-pyside6-webengine \
python3-smbus \
python3-vint \
python3-virtualenv \
python3-wheel \
qalculate \
qbittorrent \
qemu \
qjackctl \
qpdf \
qpwgraph \
qt5-webengine \
qt5ct \
qt6-base-devel \
qt6ct \
qtxdg-tools \
radeontop \
ranger \
rclone \
readline \
readline-devel \
redis \
refind \
remmina \
riff \
ripgrep \
rofi \
rofi-calc \
rofi-emoji \
rofi-pass \
rofi-rbw \
rpi-imager \
rsync \
rtkit \
runit-iptables \
rust \
rust-analyzer \
rust-doc \
rz-ghidra \
rz-ghidra-32bit \
sc-im \
scrcpy \
screen \
screenkey \
scrot \
sent \
signal-backup-decode \
simple-mtpfs \
skim \
smartmontools \
socklog \
socklog-void \
sound-juicer \
spectrum3d \
speedometer \
spotify-adblock \
sqlitebrowser \
sshguard \
starplot \
steam \
stegsnow \
stow \
streamlink \
sublime-text3 \
surf \
sxhkd \
sxiv \
syncthing \
syncthing-discosrv \
syncthing-relaysrv \
sysfsutils \
taplo \
tealdeer \
tectonic \
telegram-desktop \
termdown \
tesseract-ocr \
tesseract-ocr-eng \
tesseract-ocr-ron \
testdisk \
texlive-BibTeX \
texlive-ConTeXt \
texlive-LuaTeX \
texlive-XeTeX \
texlive-basic \
texlive-most \
texstudio \
texworks \
thunderbird \
timg \
tio \
tk-devel \
tmux \
torbrowser-launcher \
torsocks \
transmission \
transmission-qt \
tree \
tty-clock \
typst \
typst-lsp \
typstfmt \
typstyle \
ueberzug \
ufetch \
unrar \
urlview \
util-linux \
uv \
v4l-utils-32bit \
vde2 \
virt-manager \
virt-viewer \
vkBasalt \
vkBasalt-32bit \
vkQuake \
vkd3d-32bit \
void-docs \
void-docs-browse \
void-repo-multilib \
void-repo-multilib-nonfree \
void-repo-nonfree \
void-updates \
vpm \
vscode \
vsv \
w3m \
waifu2x-converter-cpp \
webp-pixbuf-loader \
websocat \
wget \
whois \
wine \
wine-32bit \
wine-gecko \
wine-mono \
wine-tools \
wineasio \
winetricks \
wireguard-tools \
wireless_tools \
wireplumber \
wireshark \
wireshark-qt \
wol \
xautolock \
xbanish \
xclip \
xcolor \
xdg-desktop-portal-gtk \
xdg-user-dirs \
xdg-user-dirs-gtk \
xdg-utils \
xdotool \
xf86-input-joystick \
xf86-input-mtrack \
xmenu \
xmirror \
xorg \
xorg-server-devel \
xoris \
xournal \
xscreensaver \
xsecurelock \
xsel \
xtools \
xvkbd \
xxd \
yad \
youtube-dl \
yt-dlp \
zathura \
zathura-cb \
zathura-djvu \
zathura-pdf-poppler \
zathura-ps \
zbar \
zbar-qt \
zig \
zip \
zls \
zola \
zoxide \
zsh \
zsh-autosuggestions \
zsh-completions \
zsh-history-substring-search \
zsh-syntax-highlighting \
zstd \
zulucrypt

echo ""

echo "Increasing max_map_count ..."
sudo sysctl -w vm.max_map_count=1048576
sysctl vm.max_map_count

echo ""

echo "Loading config files for important applications..."

# i will use move, copy, link, etc commands with their verbose options to show what is being done.
