#!/bin/bash

set -e

case $1 in

    min)
        nvidia-settings -a "[gpu:0]/GpuPowerMizerMode=0" ;;

    max)
        nvidia-settings -a "[gpu:0]/GpuPowerMizerMode=1" ;;

    auto)
        nvidia-settings -a "[gpu:0]/GpuPowerMizerMode=2"

esac

nvidia-settings -q GpuPowerMizerMode
