#!/bin/bash

#                  #
# ## ~/.xinitrc ## #
#                  #

#xrandr --output HDMI-1-0 --mode 3840x2160 -r 120 &
#xrandr --output HDMI-0 --mode 3840x2160 -r 120 &
xrandr --output HDMI-0 --mode 1920x1080 -r 240 &
xrandr --output HDMI-1-0 --mode 1920x1080 -r 240 &

xrandr -s 1920x1080 -r 144 &        # target screen resolution
xset r rate 300 30 &                # key repeat delay and speed
xset b off                          # disable bell

xrdb merge ~/.Xresources            # asset resources
picom --backend glx &               # compositor

#                  #
# ## more stuff ## #
#                  #

feh --bg-fill --no-fehbg ~/.config/backgrounds/darkflowers.jpg &        # wallpaper

libinput-gestures-setup start &                                         # Prevent accidental touch

synclient ClickPad=1                                                    # buttonless pad

synclient VertTwoFingerScroll=1                                         # enable vert scroll
synclient HorizTwoFingerScroll=1                                        # enable horiz scroll

synclient EmulateTwoFingerMinZ=300                                      # precision of scroll
synclient EmulateTwoFingerMinW=300                                      # precision of scroll

synclient PalmDetect=1                                                  # palm rejection
synclient PalmMinWidth=10                                               # size parameter
synclient PalmMinZ=200                                                  # pressure param

synclient VertScrollDelta=-200                                          # natural vert
synclient HorizScrollDelta=-200                                         # natural horiz

synclient CornerCoasting=0                                              # eliminate coasting
synclient CoastingSpeed=0                                               # eliminate coasting

synclient TapButton1=1 TapButton2=3 ClickFinger3=0                      # tap to click
synclient MinSpeed=1.25 MaxSpeed=2.5                                    # pointer speed
synclient AccelFactor=0.025                                             # acceleration

amixer --card 0 set 'Master' 100 &                                      # audio volume
amixer --card 0 set 'Mic Boost' 0 &                                     # mic boost volume
amixer --card 0 set 'Capture' 63 &                                      # capture volume # 39

sxhkd -c $HOME/.config/keybinds &                                       # keybindings

xautolock -time 10 -locker lock &                                       # xautolock screen in x minutes
# lock is a custom script that locks the screen (~/.config/lock)

syncthing serve --no-browser &>/dev/null &                              # start syncthing server

eval $(dbus-launch --sh-syntax --exit-with-x11)                         # dbus session
pipewire &                                                              # audio server

slstatus &                                                              # statusbar

~/dev/kekful_days/kekful_days.sh &                                      # custom script

setxkbmap -option caps:escape &                                         # set caps to esc

exec dwm                                                                # window manager
