#!/bin/sh

## # zsh / aliases # ##

alias grep='grep --colour=auto'
alias ls='ls --color=auto'

# shorthands
alias ll='ls -lGh'
alias la='ls -lGAh'
alias lu='ls -lSh'
alias lf='ranger'
alias du='du -sh'
alias df='df -h'
alias cl='clear'

alias am='alsamixer --card 0'
alias x='cd ~ ; startx'
alias vim='nvim'
alias vi='nvim'
alias v='nvim'

alias fzf='sk'

# directories
configdir=$HOME/.config
alias cds='cd $configdir/suckless/'

# zsh
alias zal='vim $configdir/zsh/aliases'
alias zrc='vim $configdir/zsh/zshrc'
alias zen='vim $configdir/zsh/env'

# packages
alias xbpi='sudo xbps-install'
alias xbpr='sudo xbps-remove'
alias xbpq='xbps-query -Rs'
alias xbpl='xbps-query -l'

# scripts
scriptdir=$HOME/.scripts
alias rgbhex='python $scriptdir/rgbhex.py'
alias sched='python $scriptdir/sched.py'
alias vis='python $scriptdir/vis.py'

# aesthetic
alias filmelematrix='cmatrix -C red -a'
alias colorfetch='neofetch --block_range 0 15'
alias change-bg='feh --bg-fill --no-fehbg'
alias clock='tty-clock -Dc -C 4'
alias sens='watch -n 0.1 sensors'
alias htopr='htop -C -U'
alias sxiv='sxiv -bpqra'

# tools
alias newsboat='newsboat -C ~/.config/newsboat/newsboat.conf -c ~/.config/newsboat/cache.db -u ~/.config/newsboat/urls'
alias mpv="mpv -ytdl-format='bestvideo[ext=mp4][width<=1920][height<=1080]+bestaudio[ext=m4a]'"
alias w2x="waifu2x-converter-cpp -f png --noise-level 3 -c 9 -q 100 --disable-gpu --mode noise-scale -i"
alias proton='~/.local/share/Steam/steamapps/common/Proton\ -\ Experimental/proton run'
alias protonge='~/.local/share/Steam/compatibilitytools.d/GE-Proton8-27/proton run'
alias catgirl="catgirl -h irc.libera.chat -j '#voidlinux'"
alias streamlink='streamlink --default-stream best --twitch-disable-ads --player mpv'
alias ytdlpa='yt-dlp --extract-audio --audio-quality 0 --audio-format mp3'
alias ytdlp='yt-dlp'

# envycontrol for nvidia optimus
envycontrol='/home/alphara/dev/envycontrol/envycontrol.py'
alias dedicated='sudo $envycontrol -s nvidia --coolbits 28 --verbose' # --force-comp
alias hybrid='sudo $envycontrol -s hybrid --rtd3 3 --verbose'
alias integrated='sudo $envycontrol -s integrated --verbose'
